/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.vzaigrin.examples.kafka.streams;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PageViewWithRegion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4366629394389324837L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PageViewWithRegion\",\"namespace\":\"ru.vzaigrin.examples.kafka.streams\",\"fields\":[{\"name\":\"region\",\"type\":\"string\"},{\"name\":\"pages\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PageViewWithRegion> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PageViewWithRegion> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PageViewWithRegion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PageViewWithRegion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PageViewWithRegion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PageViewWithRegion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PageViewWithRegion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PageViewWithRegion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PageViewWithRegion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence region;
  private long pages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PageViewWithRegion() {}

  /**
   * All-args constructor.
   * @param region The new value for region
   * @param pages The new value for pages
   */
  public PageViewWithRegion(java.lang.CharSequence region, java.lang.Long pages) {
    this.region = region;
    this.pages = pages;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return region;
    case 1: return pages;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: region = (java.lang.CharSequence)value$; break;
    case 1: pages = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'region' field.
   * @return The value of the 'region' field.
   */
  public java.lang.CharSequence getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * @param value the value to set.
   */
  public void setRegion(java.lang.CharSequence value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'pages' field.
   * @return The value of the 'pages' field.
   */
  public long getPages() {
    return pages;
  }


  /**
   * Sets the value of the 'pages' field.
   * @param value the value to set.
   */
  public void setPages(long value) {
    this.pages = value;
  }

  /**
   * Creates a new PageViewWithRegion RecordBuilder.
   * @return A new PageViewWithRegion RecordBuilder
   */
  public static ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder newBuilder() {
    return new ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder();
  }

  /**
   * Creates a new PageViewWithRegion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PageViewWithRegion RecordBuilder
   */
  public static ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder newBuilder(ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder other) {
    if (other == null) {
      return new ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder();
    } else {
      return new ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder(other);
    }
  }

  /**
   * Creates a new PageViewWithRegion RecordBuilder by copying an existing PageViewWithRegion instance.
   * @param other The existing instance to copy.
   * @return A new PageViewWithRegion RecordBuilder
   */
  public static ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder newBuilder(ru.vzaigrin.examples.kafka.streams.PageViewWithRegion other) {
    if (other == null) {
      return new ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder();
    } else {
      return new ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder(other);
    }
  }

  /**
   * RecordBuilder for PageViewWithRegion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PageViewWithRegion>
    implements org.apache.avro.data.RecordBuilder<PageViewWithRegion> {

    private java.lang.CharSequence region;
    private long pages;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.region)) {
        this.region = data().deepCopy(fields()[0].schema(), other.region);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pages)) {
        this.pages = data().deepCopy(fields()[1].schema(), other.pages);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PageViewWithRegion instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.vzaigrin.examples.kafka.streams.PageViewWithRegion other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.region)) {
        this.region = data().deepCopy(fields()[0].schema(), other.region);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pages)) {
        this.pages = data().deepCopy(fields()[1].schema(), other.pages);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'region' field.
      * @return The value.
      */
    public java.lang.CharSequence getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * @param value The value of 'region'.
      * @return This builder.
      */
    public ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder setRegion(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.region = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'region' field.
      * @return This builder.
      */
    public ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder clearRegion() {
      region = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pages' field.
      * @return The value.
      */
    public long getPages() {
      return pages;
    }


    /**
      * Sets the value of the 'pages' field.
      * @param value The value of 'pages'.
      * @return This builder.
      */
    public ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder setPages(long value) {
      validate(fields()[1], value);
      this.pages = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pages' field has been set.
      * @return True if the 'pages' field has been set, false otherwise.
      */
    public boolean hasPages() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pages' field.
      * @return This builder.
      */
    public ru.vzaigrin.examples.kafka.streams.PageViewWithRegion.Builder clearPages() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PageViewWithRegion build() {
      try {
        PageViewWithRegion record = new PageViewWithRegion();
        record.region = fieldSetFlags()[0] ? this.region : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.pages = fieldSetFlags()[1] ? this.pages : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PageViewWithRegion>
    WRITER$ = (org.apache.avro.io.DatumWriter<PageViewWithRegion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PageViewWithRegion>
    READER$ = (org.apache.avro.io.DatumReader<PageViewWithRegion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.region);

    out.writeLong(this.pages);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);

      this.pages = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);
          break;

        case 1:
          this.pages = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










