/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.vzaigrin.examples.kafka.streams;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PageRegion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7282187137873971795L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PageRegion\",\"namespace\":\"ru.ibs.kafka.advanced.streams\",\"fields\":[{\"name\":\"region\",\"type\":\"string\"},{\"name\":\"page\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PageRegion> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PageRegion> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PageRegion> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PageRegion> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PageRegion> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PageRegion to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PageRegion from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PageRegion instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PageRegion fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence region;
  private java.lang.CharSequence page;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PageRegion() {}

  /**
   * All-args constructor.
   * @param region The new value for region
   * @param page The new value for page
   */
  public PageRegion(java.lang.CharSequence region, java.lang.CharSequence page) {
    this.region = region;
    this.page = page;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return region;
    case 1: return page;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: region = (java.lang.CharSequence)value$; break;
    case 1: page = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'region' field.
   * @return The value of the 'region' field.
   */
  public java.lang.CharSequence getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * @param value the value to set.
   */
  public void setRegion(java.lang.CharSequence value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'page' field.
   * @return The value of the 'page' field.
   */
  public java.lang.CharSequence getPage() {
    return page;
  }


  /**
   * Sets the value of the 'page' field.
   * @param value the value to set.
   */
  public void setPage(java.lang.CharSequence value) {
    this.page = value;
  }

  /**
   * Creates a new PageRegion RecordBuilder.
   * @return A new PageRegion RecordBuilder
   */
  public static PageRegion.Builder newBuilder() {
    return new PageRegion.Builder();
  }

  /**
   * Creates a new PageRegion RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PageRegion RecordBuilder
   */
  public static PageRegion.Builder newBuilder(PageRegion.Builder other) {
    if (other == null) {
      return new PageRegion.Builder();
    } else {
      return new PageRegion.Builder(other);
    }
  }

  /**
   * Creates a new PageRegion RecordBuilder by copying an existing PageRegion instance.
   * @param other The existing instance to copy.
   * @return A new PageRegion RecordBuilder
   */
  public static PageRegion.Builder newBuilder(PageRegion other) {
    if (other == null) {
      return new PageRegion.Builder();
    } else {
      return new PageRegion.Builder(other);
    }
  }

  /**
   * RecordBuilder for PageRegion instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PageRegion>
    implements org.apache.avro.data.RecordBuilder<PageRegion> {

    private java.lang.CharSequence region;
    private java.lang.CharSequence page;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(PageRegion.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.region)) {
        this.region = data().deepCopy(fields()[0].schema(), other.region);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.page)) {
        this.page = data().deepCopy(fields()[1].schema(), other.page);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PageRegion instance
     * @param other The existing instance to copy.
     */
    private Builder(PageRegion other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.region)) {
        this.region = data().deepCopy(fields()[0].schema(), other.region);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.page)) {
        this.page = data().deepCopy(fields()[1].schema(), other.page);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'region' field.
      * @return The value.
      */
    public java.lang.CharSequence getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * @param value The value of 'region'.
      * @return This builder.
      */
    public PageRegion.Builder setRegion(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.region = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'region' field.
      * @return This builder.
      */
    public PageRegion.Builder clearRegion() {
      region = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'page' field.
      * @return The value.
      */
    public java.lang.CharSequence getPage() {
      return page;
    }


    /**
      * Sets the value of the 'page' field.
      * @param value The value of 'page'.
      * @return This builder.
      */
    public PageRegion.Builder setPage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.page = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'page' field has been set.
      * @return True if the 'page' field has been set, false otherwise.
      */
    public boolean hasPage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'page' field.
      * @return This builder.
      */
    public PageRegion.Builder clearPage() {
      page = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PageRegion build() {
      try {
        PageRegion record = new PageRegion();
        record.region = fieldSetFlags()[0] ? this.region : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.page = fieldSetFlags()[1] ? this.page : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PageRegion>
    WRITER$ = (org.apache.avro.io.DatumWriter<PageRegion>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PageRegion>
    READER$ = (org.apache.avro.io.DatumReader<PageRegion>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.region);

    out.writeString(this.page);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);

      this.page = in.readString(this.page instanceof Utf8 ? (Utf8)this.page : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);
          break;

        case 1:
          this.page = in.readString(this.page instanceof Utf8 ? (Utf8)this.page : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










